<?php

use Illuminate\Database\Seeder;
use Modules\kabupaten\models\Kabupaten;
class KabupatenTable extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table('wil_kabupaten')->delete();

        $kabupaten = [
          ["id_kab"=>"1101","id_provinsi"=>"11","name"=>"KABUPATEN SIMEULUE"],
          ["id_kab"=>"1102","id_provinsi"=>"11","name"=>"KABUPATEN ACEH SINGKIL"],
          ["id_kab"=>"1103","id_provinsi"=>"11","name"=>"KABUPATEN ACEH SELATAN"],
          ["id_kab"=>"1104","id_provinsi"=>"11","name"=>"KABUPATEN ACEH TENGGARA"],
          ["id_kab"=>"1105","id_provinsi"=>"11","name"=>"KABUPATEN ACEH TIMUR"],
          ["id_kab"=>"1106","id_provinsi"=>"11","name"=>"KABUPATEN ACEH TENGAH"],
          ["id_kab"=>"1107","id_provinsi"=>"11","name"=>"KABUPATEN ACEH BARAT"],
          ["id_kab"=>"1108","id_provinsi"=>"11","name"=>"KABUPATEN ACEH BESAR"],
          ["id_kab"=>"1109","id_provinsi"=>"11","name"=>"KABUPATEN PIDIE"],
          ["id_kab"=>"1110","id_provinsi"=>"11","name"=>"KABUPATEN BIREUEN"],
          ["id_kab"=>"1111","id_provinsi"=>"11","name"=>"KABUPATEN ACEH UTARA"],
          ["id_kab"=>"1112","id_provinsi"=>"11","name"=>"KABUPATEN ACEH BARAT DAYA"],
          ["id_kab"=>"1113","id_provinsi"=>"11","name"=>"KABUPATEN GAYO LUES"],
          ["id_kab"=>"1114","id_provinsi"=>"11","name"=>"KABUPATEN ACEH TAMIANG"],
          ["id_kab"=>"1115","id_provinsi"=>"11","name"=>"KABUPATEN NAGAN RAYA"],
          ["id_kab"=>"1116","id_provinsi"=>"11","name"=>"KABUPATEN ACEH JAYA"],
          ["id_kab"=>"1117","id_provinsi"=>"11","name"=>"KABUPATEN BENER MERIAH"],
          ["id_kab"=>"1118","id_provinsi"=>"11","name"=>"KABUPATEN PIDIE JAYA"],
          ["id_kab"=>"1171","id_provinsi"=>"11","name"=>"KOTA BANDA ACEH"],
          ["id_kab"=>"1172","id_provinsi"=>"11","name"=>"KOTA SABANG"],
          ["id_kab"=>"1173","id_provinsi"=>"11","name"=>"KOTA LANGSA"],
          ["id_kab"=>"1174","id_provinsi"=>"11","name"=>"KOTA LHOKSEUMAWE"],
          ["id_kab"=>"1175","id_provinsi"=>"11","name"=>"KOTA SUBULUSSALAM"],
          ["id_kab"=>"1201","id_provinsi"=>"12","name"=>"KABUPATEN NIAS"],
          ["id_kab"=>"1202","id_provinsi"=>"12","name"=>"KABUPATEN MANDAILING NATAL"],
          ["id_kab"=>"1203","id_provinsi"=>"12","name"=>"KABUPATEN TAPANULI SELATAN"],
          ["id_kab"=>"1204","id_provinsi"=>"12","name"=>"KABUPATEN TAPANULI TENGAH"],
          ["id_kab"=>"1205","id_provinsi"=>"12","name"=>"KABUPATEN TAPANULI UTARA"],
          ["id_kab"=>"1206","id_provinsi"=>"12","name"=>"KABUPATEN TOBA SAMOSIR"],
          ["id_kab"=>"1207","id_provinsi"=>"12","name"=>"KABUPATEN LABUHAN BATU"],
          ["id_kab"=>"1208","id_provinsi"=>"12","name"=>"KABUPATEN ASAHAN"],
          ["id_kab"=>"1209","id_provinsi"=>"12","name"=>"KABUPATEN SIMALUNGUN"],
          ["id_kab"=>"1210","id_provinsi"=>"12","name"=>"KABUPATEN DAIRI"],
          ["id_kab"=>"1211","id_provinsi"=>"12","name"=>"KABUPATEN KARO"],
          ["id_kab"=>"1212","id_provinsi"=>"12","name"=>"KABUPATEN DELI SERDANG"],
          ["id_kab"=>"1213","id_provinsi"=>"12","name"=>"KABUPATEN LANGKAT"],
          ["id_kab"=>"1214","id_provinsi"=>"12","name"=>"KABUPATEN NIAS SELATAN"],
          ["id_kab"=>"1215","id_provinsi"=>"12","name"=>"KABUPATEN HUMBANG HASUNDUTAN"],
          ["id_kab"=>"1216","id_provinsi"=>"12","name"=>"KABUPATEN PAKPAK BHARAT"],
          ["id_kab"=>"1217","id_provinsi"=>"12","name"=>"KABUPATEN SAMOSIR"],
          ["id_kab"=>"1218","id_provinsi"=>"12","name"=>"KABUPATEN SERDANG BEDAGAI"],
          ["id_kab"=>"1219","id_provinsi"=>"12","name"=>"KABUPATEN BATU BARA"],
          ["id_kab"=>"1220","id_provinsi"=>"12","name"=>"KABUPATEN PADANG LAWAS UTARA"],
          ["id_kab"=>"1221","id_provinsi"=>"12","name"=>"KABUPATEN PADANG LAWAS"],
          ["id_kab"=>"1222","id_provinsi"=>"12","name"=>"KABUPATEN LABUHAN BATU SELATAN"],
          ["id_kab"=>"1223","id_provinsi"=>"12","name"=>"KABUPATEN LABUHAN BATU UTARA"],
          ["id_kab"=>"1224","id_provinsi"=>"12","name"=>"KABUPATEN NIAS UTARA"],
          ["id_kab"=>"1225","id_provinsi"=>"12","name"=>"KABUPATEN NIAS BARAT"],
          ["id_kab"=>"1271","id_provinsi"=>"12","name"=>"KOTA SIBOLGA"],
          ["id_kab"=>"1272","id_provinsi"=>"12","name"=>"KOTA TANJUNG BALAI"],
          ["id_kab"=>"1273","id_provinsi"=>"12","name"=>"KOTA PEMATANG SIANTAR"],
          ["id_kab"=>"1274","id_provinsi"=>"12","name"=>"KOTA TEBING TINGGI"],
          ["id_kab"=>"1275","id_provinsi"=>"12","name"=>"KOTA MEDAN"],
          ["id_kab"=>"1276","id_provinsi"=>"12","name"=>"KOTA BINJAI"],
          ["id_kab"=>"1277","id_provinsi"=>"12","name"=>"KOTA PADANGSIDIMPUAN"],
          ["id_kab"=>"1278","id_provinsi"=>"12","name"=>"KOTA GUNUNGSITOLI"],
          ["id_kab"=>"1301","id_provinsi"=>"13","name"=>"KABUPATEN KEPULAUAN MENTAWAI"],
          ["id_kab"=>"1302","id_provinsi"=>"13","name"=>"KABUPATEN PESISIR SELATAN"],
          ["id_kab"=>"1303","id_provinsi"=>"13","name"=>"KABUPATEN SOLOK"],
          ["id_kab"=>"1304","id_provinsi"=>"13","name"=>"KABUPATEN SIJUNJUNG"],
          ["id_kab"=>"1305","id_provinsi"=>"13","name"=>"KABUPATEN TANAH DATAR"],
          ["id_kab"=>"1306","id_provinsi"=>"13","name"=>"KABUPATEN PADANG PARIAMAN"],
          ["id_kab"=>"1307","id_provinsi"=>"13","name"=>"KABUPATEN AGAM"],
          ["id_kab"=>"1308","id_provinsi"=>"13","name"=>"KABUPATEN LIMA PULUH KOTA"],
          ["id_kab"=>"1309","id_provinsi"=>"13","name"=>"KABUPATEN PASAMAN"],
          ["id_kab"=>"1310","id_provinsi"=>"13","name"=>"KABUPATEN SOLOK SELATAN"],
          ["id_kab"=>"1311","id_provinsi"=>"13","name"=>"KABUPATEN DHARMASRAYA"],
          ["id_kab"=>"1312","id_provinsi"=>"13","name"=>"KABUPATEN PASAMAN BARAT"],
          ["id_kab"=>"1371","id_provinsi"=>"13","name"=>"KOTA PADANG"],
          ["id_kab"=>"1372","id_provinsi"=>"13","name"=>"KOTA SOLOK"],
          ["id_kab"=>"1373","id_provinsi"=>"13","name"=>"KOTA SAWAH LUNTO"],
          ["id_kab"=>"1374","id_provinsi"=>"13","name"=>"KOTA PADANG PANJANG"],
          ["id_kab"=>"1375","id_provinsi"=>"13","name"=>"KOTA BUKITTINGGI"],
          ["id_kab"=>"1376","id_provinsi"=>"13","name"=>"KOTA PAYAKUMBUH"],
          ["id_kab"=>"1377","id_provinsi"=>"13","name"=>"KOTA PARIAMAN"],
          ["id_kab"=>"1401","id_provinsi"=>"14","name"=>"KABUPATEN KUANTAN SINGINGI"],
          ["id_kab"=>"1402","id_provinsi"=>"14","name"=>"KABUPATEN INDRAGIRI HULU"],
          ["id_kab"=>"1403","id_provinsi"=>"14","name"=>"KABUPATEN INDRAGIRI HILIR"],
          ["id_kab"=>"1404","id_provinsi"=>"14","name"=>"KABUPATEN PELALAWAN"],
          ["id_kab"=>"1405","id_provinsi"=>"14","name"=>"KABUPATEN S I A K"],
          ["id_kab"=>"1406","id_provinsi"=>"14","name"=>"KABUPATEN KAMPAR"],
          ["id_kab"=>"1407","id_provinsi"=>"14","name"=>"KABUPATEN ROKAN HULU"],
          ["id_kab"=>"1408","id_provinsi"=>"14","name"=>"KABUPATEN BENGKALIS"],
          ["id_kab"=>"1409","id_provinsi"=>"14","name"=>"KABUPATEN ROKAN HILIR"],
          ["id_kab"=>"1410","id_provinsi"=>"14","name"=>"KABUPATEN KEPULAUAN MERANTI"],
          ["id_kab"=>"1471","id_provinsi"=>"14","name"=>"KOTA PEKANBARU"],
          ["id_kab"=>"1473","id_provinsi"=>"14","name"=>"KOTA D U M A I"],
          ["id_kab"=>"1501","id_provinsi"=>"15","name"=>"KABUPATEN KERINCI"],
          ["id_kab"=>"1502","id_provinsi"=>"15","name"=>"KABUPATEN MERANGIN"],
          ["id_kab"=>"1503","id_provinsi"=>"15","name"=>"KABUPATEN SAROLANGUN"],
          ["id_kab"=>"1504","id_provinsi"=>"15","name"=>"KABUPATEN BATANG HARI"],
          ["id_kab"=>"1505","id_provinsi"=>"15","name"=>"KABUPATEN MUARO JAMBI"],
          ["id_kab"=>"1506","id_provinsi"=>"15","name"=>"KABUPATEN TANJUNG JABUNG TIMUR"],
          ["id_kab"=>"1507","id_provinsi"=>"15","name"=>"KABUPATEN TANJUNG JABUNG BARAT"],
          ["id_kab"=>"1508","id_provinsi"=>"15","name"=>"KABUPATEN TEBO"],
          ["id_kab"=>"1509","id_provinsi"=>"15","name"=>"KABUPATEN BUNGO"],
          ["id_kab"=>"1571","id_provinsi"=>"15","name"=>"KOTA JAMBI"],
          ["id_kab"=>"1572","id_provinsi"=>"15","name"=>"KOTA SUNGAI PENUH"],
          ["id_kab"=>"1601","id_provinsi"=>"16","name"=>"KABUPATEN OGAN KOMERING ULU"],
          ["id_kab"=>"1602","id_provinsi"=>"16","name"=>"KABUPATEN OGAN KOMERING ILIR"],
          ["id_kab"=>"1603","id_provinsi"=>"16","name"=>"KABUPATEN MUARA ENIM"],
          ["id_kab"=>"1604","id_provinsi"=>"16","name"=>"KABUPATEN LAHAT"],
          ["id_kab"=>"1605","id_provinsi"=>"16","name"=>"KABUPATEN MUSI RAWAS"],
          ["id_kab"=>"1606","id_provinsi"=>"16","name"=>"KABUPATEN MUSI BANYUASIN"],
          ["id_kab"=>"1607","id_provinsi"=>"16","name"=>"KABUPATEN BANYU ASIN"],
          ["id_kab"=>"1608","id_provinsi"=>"16","name"=>"KABUPATEN OGAN KOMERING ULU SELATAN"],
          ["id_kab"=>"1609","id_provinsi"=>"16","name"=>"KABUPATEN OGAN KOMERING ULU TIMUR"],
          ["id_kab"=>"1610","id_provinsi"=>"16","name"=>"KABUPATEN OGAN ILIR"],
          ["id_kab"=>"1611","id_provinsi"=>"16","name"=>"KABUPATEN EMPAT LAWANG"],
          ["id_kab"=>"1612","id_provinsi"=>"16","name"=>"KABUPATEN PENUKAL ABAB LEMATANG ILIR"],
          ["id_kab"=>"1613","id_provinsi"=>"16","name"=>"KABUPATEN MUSI RAWAS UTARA"],
          ["id_kab"=>"1671","id_provinsi"=>"16","name"=>"KOTA PALEMBANG"],
          ["id_kab"=>"1672","id_provinsi"=>"16","name"=>"KOTA PRABUMULIH"],
          ["id_kab"=>"1673","id_provinsi"=>"16","name"=>"KOTA PAGAR ALAM"],
          ["id_kab"=>"1674","id_provinsi"=>"16","name"=>"KOTA LUBUKLINGGAU"],
          ["id_kab"=>"1701","id_provinsi"=>"17","name"=>"KABUPATEN BENGKULU SELATAN"],
          ["id_kab"=>"1702","id_provinsi"=>"17","name"=>"KABUPATEN REJANG LEBONG"],
          ["id_kab"=>"1703","id_provinsi"=>"17","name"=>"KABUPATEN BENGKULU UTARA"],
          ["id_kab"=>"1704","id_provinsi"=>"17","name"=>"KABUPATEN KAUR"],
          ["id_kab"=>"1705","id_provinsi"=>"17","name"=>"KABUPATEN SELUMA"],
          ["id_kab"=>"1706","id_provinsi"=>"17","name"=>"KABUPATEN MUKOMUKO"],
          ["id_kab"=>"1707","id_provinsi"=>"17","name"=>"KABUPATEN LEBONG"],
          ["id_kab"=>"1708","id_provinsi"=>"17","name"=>"KABUPATEN KEPAHIANG"],
          ["id_kab"=>"1709","id_provinsi"=>"17","name"=>"KABUPATEN BENGKULU TENGAH"],
          ["id_kab"=>"1771","id_provinsi"=>"17","name"=>"KOTA BENGKULU"],
          ["id_kab"=>"1801","id_provinsi"=>"18","name"=>"KABUPATEN LAMPUNG BARAT"],
          ["id_kab"=>"1802","id_provinsi"=>"18","name"=>"KABUPATEN TANGGAMUS"],
          ["id_kab"=>"1803","id_provinsi"=>"18","name"=>"KABUPATEN LAMPUNG SELATAN"],
          ["id_kab"=>"1804","id_provinsi"=>"18","name"=>"KABUPATEN LAMPUNG TIMUR"],
          ["id_kab"=>"1805","id_provinsi"=>"18","name"=>"KABUPATEN LAMPUNG TENGAH"],
          ["id_kab"=>"1806","id_provinsi"=>"18","name"=>"KABUPATEN LAMPUNG UTARA"],
          ["id_kab"=>"1807","id_provinsi"=>"18","name"=>"KABUPATEN WAY KANAN"],
          ["id_kab"=>"1808","id_provinsi"=>"18","name"=>"KABUPATEN TULANGBAWANG"],
          ["id_kab"=>"1809","id_provinsi"=>"18","name"=>"KABUPATEN PESAWARAN"],
          ["id_kab"=>"1810","id_provinsi"=>"18","name"=>"KABUPATEN PRINGSEWU"],
          ["id_kab"=>"1811","id_provinsi"=>"18","name"=>"KABUPATEN MESUJI"],
          ["id_kab"=>"1812","id_provinsi"=>"18","name"=>"KABUPATEN TULANG BAWANG BARAT"],
          ["id_kab"=>"1813","id_provinsi"=>"18","name"=>"KABUPATEN PESISIR BARAT"],
          ["id_kab"=>"1871","id_provinsi"=>"18","name"=>"KOTA BANDAR LAMPUNG"],
          ["id_kab"=>"1872","id_provinsi"=>"18","name"=>"KOTA METRO"],
          ["id_kab"=>"1901","id_provinsi"=>"19","name"=>"KABUPATEN BANGKA"],
          ["id_kab"=>"1902","id_provinsi"=>"19","name"=>"KABUPATEN BELITUNG"],
          ["id_kab"=>"1903","id_provinsi"=>"19","name"=>"KABUPATEN BANGKA BARAT"],
          ["id_kab"=>"1904","id_provinsi"=>"19","name"=>"KABUPATEN BANGKA TENGAH"],
          ["id_kab"=>"1905","id_provinsi"=>"19","name"=>"KABUPATEN BANGKA SELATAN"],
          ["id_kab"=>"1906","id_provinsi"=>"19","name"=>"KABUPATEN BELITUNG TIMUR"],
          ["id_kab"=>"1971","id_provinsi"=>"19","name"=>"KOTA PANGKAL PINANG"],
          ["id_kab"=>"2101","id_provinsi"=>"21","name"=>"KABUPATEN KARIMUN"],
          ["id_kab"=>"2102","id_provinsi"=>"21","name"=>"KABUPATEN BINTAN"],
          ["id_kab"=>"2103","id_provinsi"=>"21","name"=>"KABUPATEN NATUNA"],
          ["id_kab"=>"2104","id_provinsi"=>"21","name"=>"KABUPATEN LINGGA"],
          ["id_kab"=>"2105","id_provinsi"=>"21","name"=>"KABUPATEN KEPULAUAN ANAMBAS"],
          ["id_kab"=>"2171","id_provinsi"=>"21","name"=>"KOTA B A T A M"],
          ["id_kab"=>"2172","id_provinsi"=>"21","name"=>"KOTA TANJUNG PINANG"],
          ["id_kab"=>"3101","id_provinsi"=>"31","name"=>"KABUPATEN KEPULAUAN SERIBU"],
          ["id_kab"=>"3171","id_provinsi"=>"31","name"=>"KOTA JAKARTA SELATAN"],
          ["id_kab"=>"3172","id_provinsi"=>"31","name"=>"KOTA JAKARTA TIMUR"],
          ["id_kab"=>"3173","id_provinsi"=>"31","name"=>"KOTA JAKARTA PUSAT"],
          ["id_kab"=>"3174","id_provinsi"=>"31","name"=>"KOTA JAKARTA BARAT"],
          ["id_kab"=>"3175","id_provinsi"=>"31","name"=>"KOTA JAKARTA UTARA"],
          ["id_kab"=>"3201","id_provinsi"=>"32","name"=>"KABUPATEN BOGOR"],
          ["id_kab"=>"3202","id_provinsi"=>"32","name"=>"KABUPATEN SUKABUMI"],
          ["id_kab"=>"3203","id_provinsi"=>"32","name"=>"KABUPATEN CIANJUR"],
          ["id_kab"=>"3204","id_provinsi"=>"32","name"=>"KABUPATEN BANDUNG"],
          ["id_kab"=>"3205","id_provinsi"=>"32","name"=>"KABUPATEN GARUT"],
          ["id_kab"=>"3206","id_provinsi"=>"32","name"=>"KABUPATEN TASIKMALAYA"],
          ["id_kab"=>"3207","id_provinsi"=>"32","name"=>"KABUPATEN CIAMIS"],
          ["id_kab"=>"3208","id_provinsi"=>"32","name"=>"KABUPATEN KUNINGAN"],
          ["id_kab"=>"3209","id_provinsi"=>"32","name"=>"KABUPATEN CIREBON"],
          ["id_kab"=>"3210","id_provinsi"=>"32","name"=>"KABUPATEN MAJALENGKA"],
          ["id_kab"=>"3211","id_provinsi"=>"32","name"=>"KABUPATEN SUMEDANG"],
          ["id_kab"=>"3212","id_provinsi"=>"32","name"=>"KABUPATEN INDRAMAYU"],
          ["id_kab"=>"3213","id_provinsi"=>"32","name"=>"KABUPATEN SUBANG"],
          ["id_kab"=>"3214","id_provinsi"=>"32","name"=>"KABUPATEN PURWAKARTA"],
          ["id_kab"=>"3215","id_provinsi"=>"32","name"=>"KABUPATEN KARAWANG"],
          ["id_kab"=>"3216","id_provinsi"=>"32","name"=>"KABUPATEN BEKASI"],
          ["id_kab"=>"3217","id_provinsi"=>"32","name"=>"KABUPATEN BANDUNG BARAT"],
          ["id_kab"=>"3218","id_provinsi"=>"32","name"=>"KABUPATEN PANGANDARAN"],
          ["id_kab"=>"3271","id_provinsi"=>"32","name"=>"KOTA BOGOR"],
          ["id_kab"=>"3272","id_provinsi"=>"32","name"=>"KOTA SUKABUMI"],
          ["id_kab"=>"3273","id_provinsi"=>"32","name"=>"KOTA BANDUNG"],
          ["id_kab"=>"3274","id_provinsi"=>"32","name"=>"KOTA CIREBON"],
          ["id_kab"=>"3275","id_provinsi"=>"32","name"=>"KOTA BEKASI"],
          ["id_kab"=>"3276","id_provinsi"=>"32","name"=>"KOTA DEPOK"],
          ["id_kab"=>"3277","id_provinsi"=>"32","name"=>"KOTA CIMAHI"],
          ["id_kab"=>"3278","id_provinsi"=>"32","name"=>"KOTA TASIKMALAYA"],
          ["id_kab"=>"3279","id_provinsi"=>"32","name"=>"KOTA BANJAR"],
          ["id_kab"=>"3301","id_provinsi"=>"33","name"=>"KABUPATEN CILACAP"],
          ["id_kab"=>"3302","id_provinsi"=>"33","name"=>"KABUPATEN BANYUMAS"],
          ["id_kab"=>"3303","id_provinsi"=>"33","name"=>"KABUPATEN PURBALINGGA"],
          ["id_kab"=>"3304","id_provinsi"=>"33","name"=>"KABUPATEN BANJARNEGARA"],
          ["id_kab"=>"3305","id_provinsi"=>"33","name"=>"KABUPATEN KEBUMEN"],
          ["id_kab"=>"3306","id_provinsi"=>"33","name"=>"KABUPATEN PURWOREJO"],
          ["id_kab"=>"3307","id_provinsi"=>"33","name"=>"KABUPATEN WONOSOBO"],
          ["id_kab"=>"3308","id_provinsi"=>"33","name"=>"KABUPATEN MAGELANG"],
          ["id_kab"=>"3309","id_provinsi"=>"33","name"=>"KABUPATEN BOYOLALI"],
          ["id_kab"=>"3310","id_provinsi"=>"33","name"=>"KABUPATEN KLATEN"],
          ["id_kab"=>"3311","id_provinsi"=>"33","name"=>"KABUPATEN SUKOHARJO"],
          ["id_kab"=>"3312","id_provinsi"=>"33","name"=>"KABUPATEN WONOGIRI"],
          ["id_kab"=>"3313","id_provinsi"=>"33","name"=>"KABUPATEN KARANGANYAR"],
          ["id_kab"=>"3314","id_provinsi"=>"33","name"=>"KABUPATEN SRAGEN"],
          ["id_kab"=>"3315","id_provinsi"=>"33","name"=>"KABUPATEN GROBOGAN"],
          ["id_kab"=>"3316","id_provinsi"=>"33","name"=>"KABUPATEN BLORA"],
          ["id_kab"=>"3317","id_provinsi"=>"33","name"=>"KABUPATEN REMBANG"],
          ["id_kab"=>"3318","id_provinsi"=>"33","name"=>"KABUPATEN PATI"],
          ["id_kab"=>"3319","id_provinsi"=>"33","name"=>"KABUPATEN KUDUS"],
          ["id_kab"=>"3320","id_provinsi"=>"33","name"=>"KABUPATEN JEPARA"],
          ["id_kab"=>"3321","id_provinsi"=>"33","name"=>"KABUPATEN DEMAK"],
          ["id_kab"=>"3322","id_provinsi"=>"33","name"=>"KABUPATEN SEMARANG"],
          ["id_kab"=>"3323","id_provinsi"=>"33","name"=>"KABUPATEN TEMANGGUNG"],
          ["id_kab"=>"3324","id_provinsi"=>"33","name"=>"KABUPATEN KENDAL"],
          ["id_kab"=>"3325","id_provinsi"=>"33","name"=>"KABUPATEN BATANG"],
          ["id_kab"=>"3326","id_provinsi"=>"33","name"=>"KABUPATEN PEKALONGAN"],
          ["id_kab"=>"3327","id_provinsi"=>"33","name"=>"KABUPATEN PEMALANG"],
          ["id_kab"=>"3328","id_provinsi"=>"33","name"=>"KABUPATEN TEGAL"],
          ["id_kab"=>"3329","id_provinsi"=>"33","name"=>"KABUPATEN BREBES"],
          ["id_kab"=>"3371","id_provinsi"=>"33","name"=>"KOTA MAGELANG"],
          ["id_kab"=>"3372","id_provinsi"=>"33","name"=>"KOTA SURAKARTA"],
          ["id_kab"=>"3373","id_provinsi"=>"33","name"=>"KOTA SALATIGA"],
          ["id_kab"=>"3374","id_provinsi"=>"33","name"=>"KOTA SEMARANG"],
          ["id_kab"=>"3375","id_provinsi"=>"33","name"=>"KOTA PEKALONGAN"],
          ["id_kab"=>"3376","id_provinsi"=>"33","name"=>"KOTA TEGAL"],
          ["id_kab"=>"3401","id_provinsi"=>"34","name"=>"KABUPATEN KULON PROGO"],
          ["id_kab"=>"3402","id_provinsi"=>"34","name"=>"KABUPATEN BANTUL"],
          ["id_kab"=>"3403","id_provinsi"=>"34","name"=>"KABUPATEN GUNUNG KIDUL"],
          ["id_kab"=>"3404","id_provinsi"=>"34","name"=>"KABUPATEN SLEMAN"],
          ["id_kab"=>"3471","id_provinsi"=>"34","name"=>"KOTA YOGYAKARTA"],
          ["id_kab"=>"3501","id_provinsi"=>"35","name"=>"KABUPATEN PACITAN"],
          ["id_kab"=>"3502","id_provinsi"=>"35","name"=>"KABUPATEN PONOROGO"],
          ["id_kab"=>"3503","id_provinsi"=>"35","name"=>"KABUPATEN TRENGGALEK"],
          ["id_kab"=>"3504","id_provinsi"=>"35","name"=>"KABUPATEN TULUNGAGUNG"],
          ["id_kab"=>"3505","id_provinsi"=>"35","name"=>"KABUPATEN BLITAR"],
          ["id_kab"=>"3506","id_provinsi"=>"35","name"=>"KABUPATEN KEDIRI"],
          ["id_kab"=>"3507","id_provinsi"=>"35","name"=>"KABUPATEN MALANG"],
          ["id_kab"=>"3508","id_provinsi"=>"35","name"=>"KABUPATEN LUMAJANG"],
          ["id_kab"=>"3509","id_provinsi"=>"35","name"=>"KABUPATEN JEMBER"],
          ["id_kab"=>"3510","id_provinsi"=>"35","name"=>"KABUPATEN BANYUWANGI"],
          ["id_kab"=>"3511","id_provinsi"=>"35","name"=>"KABUPATEN BONDOWOSO"],
          ["id_kab"=>"3512","id_provinsi"=>"35","name"=>"KABUPATEN SITUBONDO"],
          ["id_kab"=>"3513","id_provinsi"=>"35","name"=>"KABUPATEN PROBOLINGGO"],
          ["id_kab"=>"3514","id_provinsi"=>"35","name"=>"KABUPATEN PASURUAN"],
          ["id_kab"=>"3515","id_provinsi"=>"35","name"=>"KABUPATEN SIDOARJO"],
          ["id_kab"=>"3516","id_provinsi"=>"35","name"=>"KABUPATEN MOJOKERTO"],
          ["id_kab"=>"3517","id_provinsi"=>"35","name"=>"KABUPATEN JOMBANG"],
          ["id_kab"=>"3518","id_provinsi"=>"35","name"=>"KABUPATEN NGANJUK"],
          ["id_kab"=>"3519","id_provinsi"=>"35","name"=>"KABUPATEN MADIUN"],
          ["id_kab"=>"3520","id_provinsi"=>"35","name"=>"KABUPATEN MAGETAN"],
          ["id_kab"=>"3521","id_provinsi"=>"35","name"=>"KABUPATEN NGAWI"],
          ["id_kab"=>"3522","id_provinsi"=>"35","name"=>"KABUPATEN BOJONEGORO"],
          ["id_kab"=>"3523","id_provinsi"=>"35","name"=>"KABUPATEN TUBAN"],
          ["id_kab"=>"3524","id_provinsi"=>"35","name"=>"KABUPATEN LAMONGAN"],
          ["id_kab"=>"3525","id_provinsi"=>"35","name"=>"KABUPATEN GRESIK"],
          ["id_kab"=>"3526","id_provinsi"=>"35","name"=>"KABUPATEN BANGKALAN"],
          ["id_kab"=>"3527","id_provinsi"=>"35","name"=>"KABUPATEN SAMPANG"],
          ["id_kab"=>"3528","id_provinsi"=>"35","name"=>"KABUPATEN PAMEKASAN"],
          ["id_kab"=>"3529","id_provinsi"=>"35","name"=>"KABUPATEN SUMENEP"],
          ["id_kab"=>"3571","id_provinsi"=>"35","name"=>"KOTA KEDIRI"],
          ["id_kab"=>"3572","id_provinsi"=>"35","name"=>"KOTA BLITAR"],
          ["id_kab"=>"3573","id_provinsi"=>"35","name"=>"KOTA MALANG"],
          ["id_kab"=>"3574","id_provinsi"=>"35","name"=>"KOTA PROBOLINGGO"],
          ["id_kab"=>"3575","id_provinsi"=>"35","name"=>"KOTA PASURUAN"],
          ["id_kab"=>"3576","id_provinsi"=>"35","name"=>"KOTA MOJOKERTO"],
          ["id_kab"=>"3577","id_provinsi"=>"35","name"=>"KOTA MADIUN"],
          ["id_kab"=>"3578","id_provinsi"=>"35","name"=>"KOTA SURABAYA"],
          ["id_kab"=>"3579","id_provinsi"=>"35","name"=>"KOTA BATU"],
          ["id_kab"=>"3601","id_provinsi"=>"36","name"=>"KABUPATEN PANDEGLANG"],
          ["id_kab"=>"3602","id_provinsi"=>"36","name"=>"KABUPATEN LEBAK"],
          ["id_kab"=>"3603","id_provinsi"=>"36","name"=>"KABUPATEN TANGERANG"],
          ["id_kab"=>"3604","id_provinsi"=>"36","name"=>"KABUPATEN SERANG"],
          ["id_kab"=>"3671","id_provinsi"=>"36","name"=>"KOTA TANGERANG"],
          ["id_kab"=>"3672","id_provinsi"=>"36","name"=>"KOTA CILEGON"],
          ["id_kab"=>"3673","id_provinsi"=>"36","name"=>"KOTA SERANG"],
          ["id_kab"=>"3674","id_provinsi"=>"36","name"=>"KOTA TANGERANG SELATAN"],
          ["id_kab"=>"5101","id_provinsi"=>"51","name"=>"KABUPATEN JEMBRANA"],
          ["id_kab"=>"5102","id_provinsi"=>"51","name"=>"KABUPATEN TABANAN"],
          ["id_kab"=>"5103","id_provinsi"=>"51","name"=>"KABUPATEN BADUNG"],
          ["id_kab"=>"5104","id_provinsi"=>"51","name"=>"KABUPATEN GIANYAR"],
          ["id_kab"=>"5105","id_provinsi"=>"51","name"=>"KABUPATEN KLUNGKUNG"],
          ["id_kab"=>"5106","id_provinsi"=>"51","name"=>"KABUPATEN BANGLI"],
          ["id_kab"=>"5107","id_provinsi"=>"51","name"=>"KABUPATEN KARANG ASEM"],
          ["id_kab"=>"5108","id_provinsi"=>"51","name"=>"KABUPATEN BULELENG"],
          ["id_kab"=>"5171","id_provinsi"=>"51","name"=>"KOTA DENPASAR"],
          ["id_kab"=>"5201","id_provinsi"=>"52","name"=>"KABUPATEN LOMBOK BARAT"],
          ["id_kab"=>"5202","id_provinsi"=>"52","name"=>"KABUPATEN LOMBOK TENGAH"],
          ["id_kab"=>"5203","id_provinsi"=>"52","name"=>"KABUPATEN LOMBOK TIMUR"],
          ["id_kab"=>"5204","id_provinsi"=>"52","name"=>"KABUPATEN SUMBAWA"],
          ["id_kab"=>"5205","id_provinsi"=>"52","name"=>"KABUPATEN DOMPU"],
          ["id_kab"=>"5206","id_provinsi"=>"52","name"=>"KABUPATEN BIMA"],
          ["id_kab"=>"5207","id_provinsi"=>"52","name"=>"KABUPATEN SUMBAWA BARAT"],
          ["id_kab"=>"5208","id_provinsi"=>"52","name"=>"KABUPATEN LOMBOK UTARA"],
          ["id_kab"=>"5271","id_provinsi"=>"52","name"=>"KOTA MATARAM"],
          ["id_kab"=>"5272","id_provinsi"=>"52","name"=>"KOTA BIMA"],
          ["id_kab"=>"5301","id_provinsi"=>"53","name"=>"KABUPATEN SUMBA BARAT"],
          ["id_kab"=>"5302","id_provinsi"=>"53","name"=>"KABUPATEN SUMBA TIMUR"],
          ["id_kab"=>"5303","id_provinsi"=>"53","name"=>"KABUPATEN KUPANG"],
          ["id_kab"=>"5304","id_provinsi"=>"53","name"=>"KABUPATEN TIMOR TENGAH SELATAN"],
          ["id_kab"=>"5305","id_provinsi"=>"53","name"=>"KABUPATEN TIMOR TENGAH UTARA"],
          ["id_kab"=>"5306","id_provinsi"=>"53","name"=>"KABUPATEN BELU"],
          ["id_kab"=>"5307","id_provinsi"=>"53","name"=>"KABUPATEN ALOR"],
          ["id_kab"=>"5308","id_provinsi"=>"53","name"=>"KABUPATEN LEMBATA"],
          ["id_kab"=>"5309","id_provinsi"=>"53","name"=>"KABUPATEN FLORES TIMUR"],
          ["id_kab"=>"5310","id_provinsi"=>"53","name"=>"KABUPATEN SIKKA"],
          ["id_kab"=>"5311","id_provinsi"=>"53","name"=>"KABUPATEN ENDE"],
          ["id_kab"=>"5312","id_provinsi"=>"53","name"=>"KABUPATEN NGADA"],
          ["id_kab"=>"5313","id_provinsi"=>"53","name"=>"KABUPATEN MANGGARAI"],
          ["id_kab"=>"5314","id_provinsi"=>"53","name"=>"KABUPATEN ROTE NDAO"],
          ["id_kab"=>"5315","id_provinsi"=>"53","name"=>"KABUPATEN MANGGARAI BARAT"],
          ["id_kab"=>"5316","id_provinsi"=>"53","name"=>"KABUPATEN SUMBA TENGAH"],
          ["id_kab"=>"5317","id_provinsi"=>"53","name"=>"KABUPATEN SUMBA BARAT DAYA"],
          ["id_kab"=>"5318","id_provinsi"=>"53","name"=>"KABUPATEN NAGEKEO"],
          ["id_kab"=>"5319","id_provinsi"=>"53","name"=>"KABUPATEN MANGGARAI TIMUR"],
          ["id_kab"=>"5320","id_provinsi"=>"53","name"=>"KABUPATEN SABU RAIJUA"],
          ["id_kab"=>"5321","id_provinsi"=>"53","name"=>"KABUPATEN MALAKA"],
          ["id_kab"=>"5371","id_provinsi"=>"53","name"=>"KOTA KUPANG"],
          ["id_kab"=>"6101","id_provinsi"=>"61","name"=>"KABUPATEN SAMBAS"],
          ["id_kab"=>"6102","id_provinsi"=>"61","name"=>"KABUPATEN BENGKAYANG"],
          ["id_kab"=>"6103","id_provinsi"=>"61","name"=>"KABUPATEN LANDAK"],
          ["id_kab"=>"6104","id_provinsi"=>"61","name"=>"KABUPATEN MEMPAWAH"],
          ["id_kab"=>"6105","id_provinsi"=>"61","name"=>"KABUPATEN SANGGAU"],
          ["id_kab"=>"6106","id_provinsi"=>"61","name"=>"KABUPATEN KETAPANG"],
          ["id_kab"=>"6107","id_provinsi"=>"61","name"=>"KABUPATEN SINTANG"],
          ["id_kab"=>"6108","id_provinsi"=>"61","name"=>"KABUPATEN KAPUAS HULU"],
          ["id_kab"=>"6109","id_provinsi"=>"61","name"=>"KABUPATEN SEKADAU"],
          ["id_kab"=>"6110","id_provinsi"=>"61","name"=>"KABUPATEN MELAWI"],
          ["id_kab"=>"6111","id_provinsi"=>"61","name"=>"KABUPATEN KAYONG UTARA"],
          ["id_kab"=>"6112","id_provinsi"=>"61","name"=>"KABUPATEN KUBU RAYA"],
          ["id_kab"=>"6171","id_provinsi"=>"61","name"=>"KOTA PONTIANAK"],
          ["id_kab"=>"6172","id_provinsi"=>"61","name"=>"KOTA SINGKAWANG"],
          ["id_kab"=>"6201","id_provinsi"=>"62","name"=>"KABUPATEN KOTAWARINGIN BARAT"],
          ["id_kab"=>"6202","id_provinsi"=>"62","name"=>"KABUPATEN KOTAWARINGIN TIMUR"],
          ["id_kab"=>"6203","id_provinsi"=>"62","name"=>"KABUPATEN KAPUAS"],
          ["id_kab"=>"6204","id_provinsi"=>"62","name"=>"KABUPATEN BARITO SELATAN"],
          ["id_kab"=>"6205","id_provinsi"=>"62","name"=>"KABUPATEN BARITO UTARA"],
          ["id_kab"=>"6206","id_provinsi"=>"62","name"=>"KABUPATEN SUKAMARA"],
          ["id_kab"=>"6207","id_provinsi"=>"62","name"=>"KABUPATEN LAMANDAU"],
          ["id_kab"=>"6208","id_provinsi"=>"62","name"=>"KABUPATEN SERUYAN"],
          ["id_kab"=>"6209","id_provinsi"=>"62","name"=>"KABUPATEN KATINGAN"],
          ["id_kab"=>"6210","id_provinsi"=>"62","name"=>"KABUPATEN PULANG PISAU"],
          ["id_kab"=>"6211","id_provinsi"=>"62","name"=>"KABUPATEN GUNUNG MAS"],
          ["id_kab"=>"6212","id_provinsi"=>"62","name"=>"KABUPATEN BARITO TIMUR"],
          ["id_kab"=>"6213","id_provinsi"=>"62","name"=>"KABUPATEN MURUNG RAYA"],
          ["id_kab"=>"6271","id_provinsi"=>"62","name"=>"KOTA PALANGKA RAYA"],
          ["id_kab"=>"6301","id_provinsi"=>"63","name"=>"KABUPATEN TANAH LAUT"],
          ["id_kab"=>"6302","id_provinsi"=>"63","name"=>"KABUPATEN KOTA BARU"],
          ["id_kab"=>"6303","id_provinsi"=>"63","name"=>"KABUPATEN BANJAR"],
          ["id_kab"=>"6304","id_provinsi"=>"63","name"=>"KABUPATEN BARITO KUALA"],
          ["id_kab"=>"6305","id_provinsi"=>"63","name"=>"KABUPATEN TAPIN"],
          ["id_kab"=>"6306","id_provinsi"=>"63","name"=>"KABUPATEN HULU SUNGAI SELATAN"],
          ["id_kab"=>"6307","id_provinsi"=>"63","name"=>"KABUPATEN HULU SUNGAI TENGAH"],
          ["id_kab"=>"6308","id_provinsi"=>"63","name"=>"KABUPATEN HULU SUNGAI UTARA"],
          ["id_kab"=>"6309","id_provinsi"=>"63","name"=>"KABUPATEN TABALONG"],
          ["id_kab"=>"6310","id_provinsi"=>"63","name"=>"KABUPATEN TANAH BUMBU"],
          ["id_kab"=>"6311","id_provinsi"=>"63","name"=>"KABUPATEN BALANGAN"],
          ["id_kab"=>"6371","id_provinsi"=>"63","name"=>"KOTA BANJARMASIN"],
          ["id_kab"=>"6372","id_provinsi"=>"63","name"=>"KOTA BANJAR BARU"],
          ["id_kab"=>"6401","id_provinsi"=>"64","name"=>"KABUPATEN PASER"],
          ["id_kab"=>"6402","id_provinsi"=>"64","name"=>"KABUPATEN KUTAI BARAT"],
          ["id_kab"=>"6403","id_provinsi"=>"64","name"=>"KABUPATEN KUTAI KARTANEGARA"],
          ["id_kab"=>"6404","id_provinsi"=>"64","name"=>"KABUPATEN KUTAI TIMUR"],
          ["id_kab"=>"6405","id_provinsi"=>"64","name"=>"KABUPATEN BERAU"],
          ["id_kab"=>"6409","id_provinsi"=>"64","name"=>"KABUPATEN PENAJAM PASER UTARA"],
          ["id_kab"=>"6411","id_provinsi"=>"64","name"=>"KABUPATEN MAHAKAM HULU"],
          ["id_kab"=>"6471","id_provinsi"=>"64","name"=>"KOTA BALIKPAPAN"],
          ["id_kab"=>"6472","id_provinsi"=>"64","name"=>"KOTA SAMARINDA"],
          ["id_kab"=>"6474","id_provinsi"=>"64","name"=>"KOTA BONTANG"],
          ["id_kab"=>"6501","id_provinsi"=>"65","name"=>"KABUPATEN MALINAU"],
          ["id_kab"=>"6502","id_provinsi"=>"65","name"=>"KABUPATEN BULUNGAN"],
          ["id_kab"=>"6503","id_provinsi"=>"65","name"=>"KABUPATEN TANA TIDUNG"],
          ["id_kab"=>"6504","id_provinsi"=>"65","name"=>"KABUPATEN NUNUKAN"],
          ["id_kab"=>"6571","id_provinsi"=>"65","name"=>"KOTA TARAKAN"],
          ["id_kab"=>"7101","id_provinsi"=>"71","name"=>"KABUPATEN BOLAANG MONGONDOW"],
          ["id_kab"=>"7102","id_provinsi"=>"71","name"=>"KABUPATEN MINAHASA"],
          ["id_kab"=>"7103","id_provinsi"=>"71","name"=>"KABUPATEN KEPULAUAN SANGIHE"],
          ["id_kab"=>"7104","id_provinsi"=>"71","name"=>"KABUPATEN KEPULAUAN TALAUD"],
          ["id_kab"=>"7105","id_provinsi"=>"71","name"=>"KABUPATEN MINAHASA SELATAN"],
          ["id_kab"=>"7106","id_provinsi"=>"71","name"=>"KABUPATEN MINAHASA UTARA"],
          ["id_kab"=>"7107","id_provinsi"=>"71","name"=>"KABUPATEN BOLAANG MONGONDOW UTARA"],
          ["id_kab"=>"7108","id_provinsi"=>"71","name"=>"KABUPATEN SIAU TAGULANDANG BIARO"],
          ["id_kab"=>"7109","id_provinsi"=>"71","name"=>"KABUPATEN MINAHASA TENGGARA"],
          ["id_kab"=>"7110","id_provinsi"=>"71","name"=>"KABUPATEN BOLAANG MONGONDOW SELATAN"],
          ["id_kab"=>"7111","id_provinsi"=>"71","name"=>"KABUPATEN BOLAANG MONGONDOW TIMUR"],
          ["id_kab"=>"7171","id_provinsi"=>"71","name"=>"KOTA MANADO"],
          ["id_kab"=>"7172","id_provinsi"=>"71","name"=>"KOTA BITUNG"],
          ["id_kab"=>"7173","id_provinsi"=>"71","name"=>"KOTA TOMOHON"],
          ["id_kab"=>"7174","id_provinsi"=>"71","name"=>"KOTA KOTAMOBAGU"],
          ["id_kab"=>"7201","id_provinsi"=>"72","name"=>"KABUPATEN BANGGAI KEPULAUAN"],
          ["id_kab"=>"7202","id_provinsi"=>"72","name"=>"KABUPATEN BANGGAI"],
          ["id_kab"=>"7203","id_provinsi"=>"72","name"=>"KABUPATEN MOROWALI"],
          ["id_kab"=>"7204","id_provinsi"=>"72","name"=>"KABUPATEN POSO"],
          ["id_kab"=>"7205","id_provinsi"=>"72","name"=>"KABUPATEN DONGGALA"],
          ["id_kab"=>"7206","id_provinsi"=>"72","name"=>"KABUPATEN TOLI-TOLI"],
          ["id_kab"=>"7207","id_provinsi"=>"72","name"=>"KABUPATEN BUOL"],
          ["id_kab"=>"7208","id_provinsi"=>"72","name"=>"KABUPATEN PARIGI MOUTONG"],
          ["id_kab"=>"7209","id_provinsi"=>"72","name"=>"KABUPATEN TOJO UNA-UNA"],
          ["id_kab"=>"7210","id_provinsi"=>"72","name"=>"KABUPATEN SIGI"],
          ["id_kab"=>"7211","id_provinsi"=>"72","name"=>"KABUPATEN BANGGAI LAUT"],
          ["id_kab"=>"7212","id_provinsi"=>"72","name"=>"KABUPATEN MOROWALI UTARA"],
          ["id_kab"=>"7271","id_provinsi"=>"72","name"=>"KOTA PALU"],
          ["id_kab"=>"7301","id_provinsi"=>"73","name"=>"KABUPATEN KEPULAUAN SELAYAR"],
          ["id_kab"=>"7302","id_provinsi"=>"73","name"=>"KABUPATEN BULUKUMBA"],
          ["id_kab"=>"7303","id_provinsi"=>"73","name"=>"KABUPATEN BANTAENG"],
          ["id_kab"=>"7304","id_provinsi"=>"73","name"=>"KABUPATEN JENEPONTO"],
          ["id_kab"=>"7305","id_provinsi"=>"73","name"=>"KABUPATEN TAKALAR"],
          ["id_kab"=>"7306","id_provinsi"=>"73","name"=>"KABUPATEN GOWA"],
          ["id_kab"=>"7307","id_provinsi"=>"73","name"=>"KABUPATEN SINJAI"],
          ["id_kab"=>"7308","id_provinsi"=>"73","name"=>"KABUPATEN MAROS"],
          ["id_kab"=>"7309","id_provinsi"=>"73","name"=>"KABUPATEN PANGKAJENE DAN KEPULAUAN"],
          ["id_kab"=>"7310","id_provinsi"=>"73","name"=>"KABUPATEN BARRU"],
          ["id_kab"=>"7311","id_provinsi"=>"73","name"=>"KABUPATEN BONE"],
          ["id_kab"=>"7312","id_provinsi"=>"73","name"=>"KABUPATEN SOPPENG"],
          ["id_kab"=>"7313","id_provinsi"=>"73","name"=>"KABUPATEN WAJO"],
          ["id_kab"=>"7314","id_provinsi"=>"73","name"=>"KABUPATEN SIDENRENG RAPPANG"],
          ["id_kab"=>"7315","id_provinsi"=>"73","name"=>"KABUPATEN PINRANG"],
          ["id_kab"=>"7316","id_provinsi"=>"73","name"=>"KABUPATEN ENREKANG"],
          ["id_kab"=>"7317","id_provinsi"=>"73","name"=>"KABUPATEN LUWU"],
          ["id_kab"=>"7318","id_provinsi"=>"73","name"=>"KABUPATEN TANA TORAJA"],
          ["id_kab"=>"7322","id_provinsi"=>"73","name"=>"KABUPATEN LUWU UTARA"],
          ["id_kab"=>"7325","id_provinsi"=>"73","name"=>"KABUPATEN LUWU TIMUR"],
          ["id_kab"=>"7326","id_provinsi"=>"73","name"=>"KABUPATEN TORAJA UTARA"],
          ["id_kab"=>"7371","id_provinsi"=>"73","name"=>"KOTA MAKASSAR"],
          ["id_kab"=>"7372","id_provinsi"=>"73","name"=>"KOTA PAREPARE"],
          ["id_kab"=>"7373","id_provinsi"=>"73","name"=>"KOTA PALOPO"],
          ["id_kab"=>"7401","id_provinsi"=>"74","name"=>"KABUPATEN BUTON"],
          ["id_kab"=>"7402","id_provinsi"=>"74","name"=>"KABUPATEN MUNA"],
          ["id_kab"=>"7403","id_provinsi"=>"74","name"=>"KABUPATEN KONAWE"],
          ["id_kab"=>"7404","id_provinsi"=>"74","name"=>"KABUPATEN KOLAKA"],
          ["id_kab"=>"7405","id_provinsi"=>"74","name"=>"KABUPATEN KONAWE SELATAN"],
          ["id_kab"=>"7406","id_provinsi"=>"74","name"=>"KABUPATEN BOMBANA"],
          ["id_kab"=>"7407","id_provinsi"=>"74","name"=>"KABUPATEN WAKATOBI"],
          ["id_kab"=>"7408","id_provinsi"=>"74","name"=>"KABUPATEN KOLAKA UTARA"],
          ["id_kab"=>"7409","id_provinsi"=>"74","name"=>"KABUPATEN BUTON UTARA"],
          ["id_kab"=>"7410","id_provinsi"=>"74","name"=>"KABUPATEN KONAWE UTARA"],
          ["id_kab"=>"7411","id_provinsi"=>"74","name"=>"KABUPATEN KOLAKA TIMUR"],
          ["id_kab"=>"7412","id_provinsi"=>"74","name"=>"KABUPATEN KONAWE KEPULAUAN"],
          ["id_kab"=>"7413","id_provinsi"=>"74","name"=>"KABUPATEN MUNA BARAT"],
          ["id_kab"=>"7414","id_provinsi"=>"74","name"=>"KABUPATEN BUTON TENGAH"],
          ["id_kab"=>"7415","id_provinsi"=>"74","name"=>"KABUPATEN BUTON SELATAN"],
          ["id_kab"=>"7471","id_provinsi"=>"74","name"=>"KOTA KENDARI"],
          ["id_kab"=>"7472","id_provinsi"=>"74","name"=>"KOTA BAUBAU"],
          ["id_kab"=>"7501","id_provinsi"=>"75","name"=>"KABUPATEN BOALEMO"],
          ["id_kab"=>"7502","id_provinsi"=>"75","name"=>"KABUPATEN GORONTALO"],
          ["id_kab"=>"7503","id_provinsi"=>"75","name"=>"KABUPATEN POHUWATO"],
          ["id_kab"=>"7504","id_provinsi"=>"75","name"=>"KABUPATEN BONE BOLANGO"],
          ["id_kab"=>"7505","id_provinsi"=>"75","name"=>"KABUPATEN GORONTALO UTARA"],
          ["id_kab"=>"7571","id_provinsi"=>"75","name"=>"KOTA GORONTALO"],
          ["id_kab"=>"7601","id_provinsi"=>"76","name"=>"KABUPATEN MAJENE"],
          ["id_kab"=>"7602","id_provinsi"=>"76","name"=>"KABUPATEN POLEWALI MANDAR"],
          ["id_kab"=>"7603","id_provinsi"=>"76","name"=>"KABUPATEN MAMASA"],
          ["id_kab"=>"7604","id_provinsi"=>"76","name"=>"KABUPATEN MAMUJU"],
          ["id_kab"=>"7605","id_provinsi"=>"76","name"=>"KABUPATEN MAMUJU UTARA"],
          ["id_kab"=>"7606","id_provinsi"=>"76","name"=>"KABUPATEN MAMUJU TENGAH"],
          ["id_kab"=>"8101","id_provinsi"=>"81","name"=>"KABUPATEN MALUKU TENGGARA BARAT"],
          ["id_kab"=>"8102","id_provinsi"=>"81","name"=>"KABUPATEN MALUKU TENGGARA"],
          ["id_kab"=>"8103","id_provinsi"=>"81","name"=>"KABUPATEN MALUKU TENGAH"],
          ["id_kab"=>"8104","id_provinsi"=>"81","name"=>"KABUPATEN BURU"],
          ["id_kab"=>"8105","id_provinsi"=>"81","name"=>"KABUPATEN KEPULAUAN ARU"],
          ["id_kab"=>"8106","id_provinsi"=>"81","name"=>"KABUPATEN SERAM BAGIAN BARAT"],
          ["id_kab"=>"8107","id_provinsi"=>"81","name"=>"KABUPATEN SERAM BAGIAN TIMUR"],
          ["id_kab"=>"8108","id_provinsi"=>"81","name"=>"KABUPATEN MALUKU BARAT DAYA"],
          ["id_kab"=>"8109","id_provinsi"=>"81","name"=>"KABUPATEN BURU SELATAN"],
          ["id_kab"=>"8171","id_provinsi"=>"81","name"=>"KOTA AMBON"],
          ["id_kab"=>"8172","id_provinsi"=>"81","name"=>"KOTA TUAL"],
          ["id_kab"=>"8201","id_provinsi"=>"82","name"=>"KABUPATEN HALMAHERA BARAT"],
          ["id_kab"=>"8202","id_provinsi"=>"82","name"=>"KABUPATEN HALMAHERA TENGAH"],
          ["id_kab"=>"8203","id_provinsi"=>"82","name"=>"KABUPATEN KEPULAUAN SULA"],
          ["id_kab"=>"8204","id_provinsi"=>"82","name"=>"KABUPATEN HALMAHERA SELATAN"],
          ["id_kab"=>"8205","id_provinsi"=>"82","name"=>"KABUPATEN HALMAHERA UTARA"],
          ["id_kab"=>"8206","id_provinsi"=>"82","name"=>"KABUPATEN HALMAHERA TIMUR"],
          ["id_kab"=>"8207","id_provinsi"=>"82","name"=>"KABUPATEN PULAU MOROTAI"],
          ["id_kab"=>"8208","id_provinsi"=>"82","name"=>"KABUPATEN PULAU TALIABU"],
          ["id_kab"=>"8271","id_provinsi"=>"82","name"=>"KOTA TERNATE"],
          ["id_kab"=>"8272","id_provinsi"=>"82","name"=>"KOTA TIDORE KEPULAUAN"],
          ["id_kab"=>"9101","id_provinsi"=>"91","name"=>"KABUPATEN FAKFAK"],
          ["id_kab"=>"9102","id_provinsi"=>"91","name"=>"KABUPATEN KAIMANA"],
          ["id_kab"=>"9103","id_provinsi"=>"91","name"=>"KABUPATEN TELUK WONDAMA"],
          ["id_kab"=>"9104","id_provinsi"=>"91","name"=>"KABUPATEN TELUK BINTUNI"],
          ["id_kab"=>"9105","id_provinsi"=>"91","name"=>"KABUPATEN MANOKWARI"],
          ["id_kab"=>"9106","id_provinsi"=>"91","name"=>"KABUPATEN SORONG SELATAN"],
          ["id_kab"=>"9107","id_provinsi"=>"91","name"=>"KABUPATEN SORONG"],
          ["id_kab"=>"9108","id_provinsi"=>"91","name"=>"KABUPATEN RAJA AMPAT"],
          ["id_kab"=>"9109","id_provinsi"=>"91","name"=>"KABUPATEN TAMBRAUW"],
          ["id_kab"=>"9110","id_provinsi"=>"91","name"=>"KABUPATEN MAYBRAT"],
          ["id_kab"=>"9111","id_provinsi"=>"91","name"=>"KABUPATEN MANOKWARI SELATAN"],
          ["id_kab"=>"9112","id_provinsi"=>"91","name"=>"KABUPATEN PEGUNUNGAN ARFAK"],
          ["id_kab"=>"9171","id_provinsi"=>"91","name"=>"KOTA SORONG"],
          ["id_kab"=>"9401","id_provinsi"=>"94","name"=>"KABUPATEN MERAUKE"],
          ["id_kab"=>"9402","id_provinsi"=>"94","name"=>"KABUPATEN JAYAWIJAYA"],
          ["id_kab"=>"9403","id_provinsi"=>"94","name"=>"KABUPATEN JAYAPURA"],
          ["id_kab"=>"9404","id_provinsi"=>"94","name"=>"KABUPATEN NABIRE"],
          ["id_kab"=>"9408","id_provinsi"=>"94","name"=>"KABUPATEN KEPULAUAN YAPEN"],
          ["id_kab"=>"9409","id_provinsi"=>"94","name"=>"KABUPATEN BIAK NUMFOR"],
          ["id_kab"=>"9410","id_provinsi"=>"94","name"=>"KABUPATEN PANIAI"],
          ["id_kab"=>"9411","id_provinsi"=>"94","name"=>"KABUPATEN PUNCAK JAYA"],
          ["id_kab"=>"9412","id_provinsi"=>"94","name"=>"KABUPATEN MIMIKA"],
          ["id_kab"=>"9413","id_provinsi"=>"94","name"=>"KABUPATEN BOVEN DIGOEL"],
          ["id_kab"=>"9414","id_provinsi"=>"94","name"=>"KABUPATEN MAPPI"],
          ["id_kab"=>"9415","id_provinsi"=>"94","name"=>"KABUPATEN ASMAT"],
          ["id_kab"=>"9416","id_provinsi"=>"94","name"=>"KABUPATEN YAHUKIMO"],
          ["id_kab"=>"9417","id_provinsi"=>"94","name"=>"KABUPATEN PEGUNUNGAN BINTANG"],
          ["id_kab"=>"9418","id_provinsi"=>"94","name"=>"KABUPATEN TOLIKARA"],
          ["id_kab"=>"9419","id_provinsi"=>"94","name"=>"KABUPATEN SARMI"],
          ["id_kab"=>"9420","id_provinsi"=>"94","name"=>"KABUPATEN KEEROM"],
          ["id_kab"=>"9426","id_provinsi"=>"94","name"=>"KABUPATEN WAROPEN"],
          ["id_kab"=>"9427","id_provinsi"=>"94","name"=>"KABUPATEN SUPIORI"],
          ["id_kab"=>"9428","id_provinsi"=>"94","name"=>"KABUPATEN MAMBERAMO RAYA"],
          ["id_kab"=>"9429","id_provinsi"=>"94","name"=>"KABUPATEN NDUGA"],
          ["id_kab"=>"9430","id_provinsi"=>"94","name"=>"KABUPATEN LANNY JAYA"],
          ["id_kab"=>"9431","id_provinsi"=>"94","name"=>"KABUPATEN MAMBERAMO TENGAH"],
          ["id_kab"=>"9432","id_provinsi"=>"94","name"=>"KABUPATEN YALIMO"],
          ["id_kab"=>"9433","id_provinsi"=>"94","name"=>"KABUPATEN PUNCAK"],
          ["id_kab"=>"9434","id_provinsi"=>"94","name"=>"KABUPATEN DOGIYAI"],
          ["id_kab"=>"9435","id_provinsi"=>"94","name"=>"KABUPATEN INTAN JAYA"],
          ["id_kab"=>"9436","id_provinsi"=>"94","name"=>"KABUPATEN DEIYAI"],
          ["id_kab"=>"9471","id_provinsi"=>"94","name"=>"KOTA JAYAPURA"]
		];

		Kabupaten::insert($kabupaten);
    }
}
